[FEAT] 소셜 로그인 구현
sopt-makers/sopt-auth-backend pull request #14
Opened 2024-11-16 17:18 UTC by sung-silver

## Related Issue 🚀
- closed #8

## Work Description ✏️
- AppleProperty, GoogleProperty: 프로퍼티 값을 불러오기 위해서 추가
- Okhttp3Config, GsonConfig: 번호 인증에서 사용된 라이브러리를 소셜 로그인 시에도 사용할 수 있도록 Config 파일을 따로 만들어 재사용할 수 있게 했습니다
  - 동규오빠 번호 인증 생성에 로직에서는 반영하지 않았어요!
- external.oauth 패키지
  - OAuthService: 각 플랫폼에서 인증 로직에 대해 필수로 구현해야하는 메서드(getIdTokenByCode)를 정의한 인터페이스 
    - AppleAuthService: 애플 인증 로직 구현
    - GoogleAuthService: 구글 인증 로직 구현 
  - OAuthPlatformService: 사용자 요청에 포함된 Platform을 확인하여 해당 플랫폼 인증 로직을 제공하는 클래스 

## PR Point 📸

- 소셜 로그인 요청을 보낼 때 필터에서 그 요청이 들어오면 처리할수도 있고, 모든 권한에 허용하고 controller에서 로그인 처리를 할 수도 있다고 생각하는데요, 저는 보통 컨트롤러에서 처리했었는데 구현하다보니 필터에서 처리하고자 하실수도 있겠다 싶어서 애플/구글에서 code를 통해 authPlatformId를 조회해오는 로직까지 구현하여 PR을 날리게 되었습니다! 이에 대한 의견 달아주시면 그에 맞춰서 추가로 커밋 남기겠습니다
- 노션에 남겨둘 application.properties 내용은 이전 operation 서버에서 구현되어 있던 설정 값을 참고하였습니다! 아마 플그에서 사용하는 설정 값과 동일하게 유지해야 할 부분이 있을 것 같은데 이 부분은 파악해서 다시 반영해두도록 하겠습니다
  - 이렇게 생각한 이유는 다음 기수에서 플폼과 플그에서 같은 authPlatformId를 가져야 데이터베이스 이관 시에도 사용자들이 원활하게 서비스를 이용할 수 있다는 생각이 들었기 때문입니다!

2024-11-17 11:19 UTC, hyunw9 requested changes
우선 고생하셨습니다 ! 볼륨이 큰데 꼼꼼하게 구현하셨군요 ! 

코드 살펴보며 가독성 측면에서 개선할 수 있는 부분에 대해서 간단하게 적어보았습니다 ! 가볍게 읽어주시면 좋을 것 같습니다 .

또한 현재 테스트 코드가 확인이 안되고 있는데, 한꺼번에 올리기 위함인지가 궁금합니다 !

2024-11-17 11:19 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
> +public class AppleAuthService implements OAuthService {
`P5`
개행 한줄 부탁드립니다 !

2024-11-17 11:19 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
> +  private static final String TOKEN_URL = "https://appleid.apple.com/auth/token";
`P2`
JWT Token Expiration 과 같이, 만료시간과 같은 부분은 Property화 하여 관리해도 좋을 것 같다는 생각입니다 !

2024-11-17 11:19 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
> +                () -> new ClientRequestException(ClientError.FAIL_READ_APPLE_PRIVATE_KEY_FILE));
`P4`
해당 부분 불필요한 개행이 존재하는 것 같아요!

2024-11-17 11:19 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
> +      PrivateKeyInfo privateKeyInfo = (PrivateKeyInfo) pemParser.readObject();
`P2`
 위 부분은 `JwtAuthProvider.class`와 같이 try-with-resource 형식을 사용해 구현해도 좋을 것 같습니다 ! 
Reader 관련 자원은 close()가 필요한데, 해당 기능을 이용하면 코드 블록 종료 시 안전하게 자원 해제가 가능합니다.

2024-11-17 11:19 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
> +        .addHeader("Accept", "application/json")
`P3`
Header와 관련된 부분은 `property` / `static constant`를 활용하는 건 어떨까요 ?

2024-11-17 11:19 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
> +    throw new ClientResponseException(ClientError.APPLE_RESPONSE_UNAVAILABLE);
`P4` 
`Static import` 하면 가독성 측면에서 더 좋을 것 같아요 !

2024-11-17 11:19 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/external/oauth/GoogleAuthService.java
> +  private final GoogleProperty googleProperty;
`P2`
제가 생각했을 때는 GRANT_TYPE, HOST와 같은 외부 벤더와 통신하기 위한 고정값은, property가 가지는 편이 더 적합하다고 생각하는데요 ! 성은님의 생각은 어떠하신지 궁금합니다!!

2024-11-17 11:19 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/external/oauth/GoogleAuthService.java
> +      throw new ClientResponseException(ClientError.GOOGLE_RESPONSE_UNAVAILABLE);
`P3`
 Exception Static import 하면 좋을 것 같습니다 !

2024-11-17 11:19 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/external/oauth/GoogleAuthService.java
> +  }
`P3` 
`parseXXX`의 함수명을 가지고 있기 때문에, 기본 리턴 값이 바깥에 나와있는 부분이 더 보기 좋을 것 같다는 개인적인 의견입니다 ! 

```
if (isBodyNull) {
    throw new ClientResponseException(ClientError.GOOGLE_RESPONSE_UNAVAILABLE);
}
String responseBody = response.body().toString();
return gson.fromJson(responseBody, IdTokenResponse.class);
```

이런 방법은 어떨까요 ?!

2024-11-17 13:46 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
> +public class AppleAuthService implements OAuthService {
클래스 시작과 변수 사이는 붙여쓰는 것으로 알고 있습니다..!!

2024-11-17 13:46 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
> +                () -> new ClientRequestException(ClientError.FAIL_READ_APPLE_PRIVATE_KEY_FILE));
변수 선언부와 실행부 사이는 한 줄 띄는것으로 알고있습니다! 아마 제 코드에서 모든 함수가 이런 컨벤션으로 작성되어 있을거에요..!

2024-11-17 13:46 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
> +      PrivateKeyInfo privateKeyInfo = (PrivateKeyInfo) pemParser.readObject();
사실 getPrivateKey 함수를 잘게 쪼개서 작성했었는데 오히려 가독성이 떨어지는 것 같더라고요.. 자원과 관련된 부분에 대해서한 함수로 분리해보겠습니다!

2024-11-17 13:46 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/external/oauth/GoogleAuthService.java
> +  private final GoogleProperty googleProperty;
저희 서비스와 관련된 내용이라면 Property에 들어가도 좋지만 이미 소셜 로그인 구현에 대한 내용들(GRANT, HOST 등)은 외부벤더에서 우리 인증서비스 사용하려면 이렇게 해~ 라고 명시를 하고 있어서 시크릿과 리다이렉트 주소 정도만 Property에 담았긴한데, 동규오빠 생각도 궁금합니다! @yummygyudon

2024-11-17 13:46 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/external/oauth/GoogleAuthService.java
> +  }
오 좋은 것 같네요 감사합니다!

2024-11-17 13:49 UTC, sung-silver commented
> 우선 고생하셨습니다 ! 볼륨이 큰데 꼼꼼하게 구현하셨군요 !
> 
> 코드 살펴보며 가독성 측면에서 개선할 수 있는 부분에 대해서 간단하게 적어보았습니다 ! 가볍게 읽어주시면 좋을 것 같습니다 .
> 
> 또한 현재 테스트 코드가 확인이 안되고 있는데, 한꺼번에 올리기 위함인지가 궁금합니다 !

- PR Point에 남긴 것 처럼 usecase 부분의 코드가 완성이 아니고 고민점(컨트롤러에서 로그인을 구현 or 필터에서 로그인을 처리)이 생겨 중간에 날린 PR이기에 테스트코드가 포함되지 않았습니다! 만약 볼륨이 크다면 외부 서비스에 대한 테스트코드만 추가하여 먼저 머지하면 될 것 같네요 
- 동규오빠 의견까지 듣고 모두 구현 + 테스트코드 or 소셜 인증 과정에 대한 테스트코드만 작성하고 머지하도록 하겠습니다!

2024-11-18 08:24 UTC, yummygyudon approved these changes
구현 고생 많으셨습니다!!

사실 OkHttp Client와 Gson 라이브러리를 주입받아 사용한 이유는
Gabia 측 요구 사항 / 예시 코드를 참고해서 빠르게 구현하고자였긴 했는데

두 라이브러리 모두 생태계 내에서 활발히 사용되고 꾸준히 업데이트 되고 있으니 무관하겠죠...?!
(@sung-silver , @hyunw9 두 분의 의견이 궁금하긴 합니다~!!)

---
- 전체적으로 상수화하면 훨씬 깔끔해질 것 같아요!! :)

2024-11-18 08:24 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/support/code/external/failure/ClientError.java
> +  INVALID_APPLE_AUTH_CODE(HttpStatus.BAD_REQUEST, "유효하지 않은 Apple 인증 code 입니다.");
`p3`

`BAD_REQUEST` 와 `INTERNAL_SERVER_ERROR` 가 섞여 있으니 파악하기가 어려운 . 것같아요!!

개행을 통해 동일한 status code를 가진 객체들 집단을 분리해주는 것도 좋아보여요!!

ex.
```java
  // 400
  INVALID_GOOGLE_AUTH_CODE(HttpStatus.BAD_REQUEST, "유효하지 않은 Google 인증 code 입니다"),
  INVALID_APPLE_AUTH_CODE(HttpStatus.BAD_REQUEST, "유효하지 않은 Apple 인증 code 입니다.");

  // 500
  INVALID_ID_TOKEN(HttpStatus.INTERNAL_SERVER_ERROR, "유효하지 않은 id token 입니다."),
  FAIL_READ_APPLE_PRIVATE_KEY_FILE(
      HttpStatus.INTERNAL_SERVER_ERROR, "Apple private key 파일을 읽는데 실패했습니다."),
  APPLE_RESPONSE_UNAVAILABLE(HttpStatus.INTERNAL_SERVER_ERROR, "APPLE 인증 요청 결과 반환된 값이 없습니다."),
  APPLE_INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "Apple 인증 서버로부터 응답을 받지 못했습니다."),
  GOOGLE_RESPONSE_UNAVAILABLE(HttpStatus.INTERNAL_SERVER_ERROR, "GOOGLE 인증 요청 결과 반환된 값이 없습니다."),
```

2024-11-18 08:24 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/usecase/auth/port/in/AuthenticateSocialAccountUsecase.java
> +  SocialAccount authenticate(AuthenticateSocialAccountCommand command);
`P2`

저희 Return 타입도 Info 객체를 따로 정의해서 도메인 객체를 온전히 숨기자고 했던 것으로 기억합니다!!
`SocialAccount`는 도메인 객체였던 것으로 기억해서!!

2024-11-18 08:24 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/usecase/auth/port/out/OAuthPlatformPort.java
> +import sopt.makers.authentication.domain.auth.*;
`P4`

오라?! 왜 와일드 카드로 되어있는교?!
`AuthPlatform` 밖에 없어보이는디

2024-11-18 08:24 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/usecase/auth/port/in/AuthenticateSocialAccountUsecase.java
> +import sopt.makers.authentication.domain.auth.*;
`P4`

와일드 카드!

2024-11-18 08:24 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/usecase/auth/service/AuthenticateSocialAccountService.java
> +import lombok.*;
`P4`

전부 와일드 카드군요!!

2024-11-18 08:24 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
> +        .add("grant_type", GRANT_TYPE)
`P4`

상수화해도 좋을 것 같네요!!

2024-11-18 08:24 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
> +        .setHeaderParam("alg", "ES256")
`P4`

요런 친구들도 AuthJwtConstant 등으로 상수화해서 사용해도 좋을 것 같아요!!

2024-11-18 08:27 UTC, yummygyudon commented
> > 우선 고생하셨습니다 ! 볼륨이 큰데 꼼꼼하게 구현하셨군요 !
> > 코드 살펴보며 가독성 측면에서 개선할 수 있는 부분에 대해서 간단하게 적어보았습니다 ! 가볍게 읽어주시면 좋을 것 같습니다 .
> > 또한 현재 테스트 코드가 확인이 안되고 있는데, 한꺼번에 올리기 위함인지가 궁금합니다 !
> 
> * PR Point에 남긴 것 처럼 usecase 부분의 코드가 완성이 아니고 고민점(컨트롤러에서 로그인을 구현 or 필터에서 로그인을 처리)이 생겨 중간에 날린 PR이기에 테스트코드가 포함되지 않았습니다! 만약 볼륨이 크다면 외부 서비스에 대한 테스트코드만 추가하여 먼저 머지하면 될 것 같네요
> * 동규오빠 의견까지 듣고 모두 구현 + 테스트코드 or 소셜 인증 과정에 대한 테스트코드만 작성하고 머지하도록 하겠습니다!

요고까지 확인했습니다!!! 😚

저의 경우, 테스트 코드가 없는 것은
아직 기능상 생성하는 것까지밖에 없었어서 유의미한 테스트 요소가 없어서 + 일정이 많이 연기되어서 입니다...ㅋㅋㅋㅋㅋ

테스트 코드도 중요하지만 무엇보다 중요한 것은.... "기한"...이기에..
그래도 최대한 신경쓰도록 하겠습니닷!!

2024-11-19 11:12 UTC, hyunw9 approved these changes

2024-11-19 11:40 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
> +        .add("grant_type", GRANT_TYPE)
key도 상수화

2024-11-19 13:21 UTC, hyunw9 approved these changes

2024-11-19 13:21 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/external/oauth/OAuthPlatformService.java
> +  private final GoogleAuthService googleAuthService;
`P4` 

현재 Service 컴포넌트가 Service를 참조하고 있어 조금 어색한 것 같습니다 ! 
***AuthProvider로 수정하는 건 어떨까요 ?!

2024-11-19 15:03 UTC, hyunw9 approved these changes

2024-11-23 16:27 UTC, sung-silver commented
- 변경된 부분은 다음과 같습니다
1. SocialAccountInfo 분리 -> Command와 유사하게 유즈케이스내에 정의했습니다
2. KeyFileUtil 분리 -> 애플 인증 로직에서 파일을 불러오는 로직이 포함되는 것이 책임이 많은 것 같아 Util 객체로 분리했습니다!
3. usecase의 소셜 플랫폼 인증과 관련된 out port의 이름을 OAuthAuthenticator로 변경했습니다
4. 3번 변경사항에 따라 OAuth 서비스 로직들은 다시 이름을 Service로 변경해두었습니다

작업이 늦어져서 죄송합니다!

2024-11-23 16:28 UTC, hyunw9 commented
👍👍

2024-11-23 16:36 UTC, merged