[FEAT/#23] 소셜 계정 변경하기 API 구현
sopt-makers/sopt-auth-backend pull request #24
Opened 2024-12-05 04:45 UTC by sung-silver

## Related Issue 🚀
- closed #23

## Work Description ✏️
- 소셜 계정 변경하기 API를 구현했습니다
- ResponseUtil에 BaseResponse를 생성하여 ResponseEntity를 반환하는 메서드를 만들었습니다
- AuthController에 기존에 존재하던 API에는 모두 반영했습니다
- flow: 인증된 사용자의 핸드폰 번호를 받아 회원을 조회하여 소셜 계정을 업데이트하는 로직입니다

## PR Point 📸

- 두분 PR이 아직 머지되지 않아서 제가 다 변경한다고하고 변경을 못했네요 ^^... 참고부탁드립니다

2024-12-05 11:25 UTC, yummygyudon requested changes
작업하시느라 고생하셨어요!!

몇 가지 논의해보고 싶은 부분에 대해 리뷰 남겨놨으니 편하게 얘기해보아요!!
(저랑 조금 겹치는 작업 범위가 보이는데...충돌이 두렵다...!)

2024-12-05 11:25 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/database/rdb/repository/UserRegister.java
> +    return updatedUserEntity.toDomain();
`P2` 

저는 개인적으로 Database 헬퍼 객체로서 도메인 객체를 반환하는 것은 이르다고 생각합니다!

헬퍼 객체의 역할은 "Transaction 관련 부가적인 처리까지만 담당한다 (ex. 존재하지 않을 경우 예외 발생 등)"로 제한하는 것이 좋다고 생각해요!!
"도메인"객체로의 변환은 "OutPort`인 Repository 구현체에서 담당하는게 역할 분리 측면에서 더 적합하다고 생각하는데 어떻게 생각하시나요?!
(cc. @hyunw9 )

2024-12-05 11:25 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/database/rdb/repository/UserRetriever.java
> +        userJpaRepository.findByPhone(phone).orElseThrow(() -> new UserException(NOT_FOUND_PHONE));
아 제가 구현한 부분엔
NOT_FOUND_USER 로 통일시켜버렸는데
이게 맞겠네...ㅋㅋㅋㅋ쿜쿜

2024-12-05 11:25 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/usecase/auth/service/UpdateSocialAccountService.java
> +    userRepository.save(userId, user);
`P2`

음 저는 해당 객체가 실제로 트랜젝션 메서드를 정의하는 Spring Data JPA의 `JpaRepository` 인터페이스가 아닌
"Out Port" 객체의 메서드이기 때문에
현재 수행하는 기능의 의미를 담아 내부적으로는 `JpaRepository` 의 `save` 메서드를 호출할지라도 `UserRepository` Out Port 인터페이스에서는 `update`라는 메서드를 정의해서 구현하는 것이 더 좋다고 생각해요!

더 나아가서 `user.updateSocialAccount(socialAccount);` 로직까지 내부적으로 분리할 수 있을 것 같다는 생각이 듭니다.

```java
// UpdateSocialAccountService
  @Override
  public boolean update(UpdateSocialAccountCommand command) {
    ...
    SocialAccount updatedSocialAccount = SocialAccount.of(authPlatformId, command.authPlatform());
    userRepository.update(userId, user, updatedSocialAccount0;
  }
// UserRepositoryImpl
  public void update(Long userId, User user, SocialAccount updatedAccount) {
    user.setId(userId);
    user.updateSocialAccount(updatedAccount);
    register.save(user);
  }
```
한 번 예시로 적어보았는데 어떨지 모르겠네요!!
개인적인 의견이니 편하게 이견있으시다면 말씀해주세요!

2024-12-05 13:21 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/database/rdb/repository/UserRetriever.java
> +        userJpaRepository.findByPhone(phone).orElseThrow(() -> new UserException(NOT_FOUND_PHONE));
dev 반영할 때 제거로 남겼습니다!!

2024-12-05 13:40 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/database/rdb/repository/UserRegister.java
> +    return updatedUserEntity.toDomain();
저는 완전 찬성해요! 좋은 리뷰 감사합니다 :-)

2024-12-05 13:41 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/usecase/auth/service/UpdateSocialAccountService.java
> +    userRepository.save(userId, user);
디스코드 과외 잘 받았습니다 킥킥

2024-12-05 13:47 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/database/rdb/repository/UserRegister.java
> +    return updatedUserEntity.toDomain();
저도 동의합니다 ~ 의존성이 도메인 쪽으로 흐르는게 올바른거 가타요

2024-12-06 00:27 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/database/rdb/repository/UserRegister.java
> +    return updatedUserEntity.toDomain();
넵 여기 맞춰서 변경했습니다!

2024-12-07 14:49 UTC, yummygyudon approved these changes

2024-12-07 14:51 UTC, hyunw9 approved these changes

2024-12-07 15:23 UTC, merged