[FEAT/#17] 가입 계정 플랫폼 조회 기능 구현
sopt-makers/sopt-auth-backend pull request #27
Opened 2024-12-06 15:41 UTC by yummygyudon

## Related Issue 🚀
- closed #17 

## Work Description ✏️
- 가입 계정 소셜 플랫폼 정보 조회 기능을 구현했습니다.
  - 이름 및 전화번호 기반으로 조회합니다.

### TODO
> #22 PR  & #26 PR 머지 이후, 버전 간 불일치 해결 및 정상 Bean Factory 준비가 가능한 상태로 반연한 후에 Rebase 받아 진행합니다.
- [ ] Usecase Test
- [ ] Controller Test

## PR Point 📸

### ※ Request Spec
```
Request Parmeter :: name (optional)
Request Parmeter :: phone (required)
```
본래 보통의 유저 정보 조회의 경우, "유저 식별 정보(User ID)" 기반으로 조회하는 경우가 대다수입니다.

하지만 본 기능의 경우, "**비로그인 상황**"에서 요청되는 "가입 계정 조회"이기 때문에 유저 식별 정보를 통해 클라이언트와 통신하는 것은 바람직하지 않다고 판단함과 동시에 `GET` 메소드의 API 이기 때문에
본 PR과 같이 `name` & `phone`을 **파라미터**로 담아 조회할 수 있도록 구현했습니다.

(`name` parameter의 경우, 본래 필수적인 요소이긴 하나 앱 Native View 내 개인정보 수집으로 인한 앱 배포 심사 통과가 어렵다는 점을 감안하여 `required=false` 옵션을 추가해 해당 파라미터가 지금으로선 존재하진 않더라도 기능할 수 있도록 구현했습니다.)

이러한 방식이 바람직한지 계속해서 고민 중에 있습니다!
위 방식에 이견이나 우려점이 있으시다면 편하게 말씀해주세요!!

2024-12-09 19:09 UTC, sung-silver requested changes
리뷰 확인 부탁드립니다!

2024-12-09 19:09 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/application/auth/api/SocialAccountApiController.java
> +  }
`p2`

저희 저번에 ResponseUtil 사용하기로 했어서 변경되어야 할 것 같습니다!

2024-12-09 19:09 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/application/auth/api/SocialAccountApiController.java
> +import org.springframework.web.bind.annotation.*;
`p3`

와일드카드!!

2024-12-09 19:09 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/support/code/domain/success/AuthSuccess.java
>    AUTHENTICATE_SOCIAL_ACCOUNT(HttpStatus.OK, "소셜 로그인에 성공했습니다.");
`p3`

200 다음에 201이 오도록 두 개의 위치가 변경되면 더 좋을 것 같습니다!

2024-12-09 19:09 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/support/code/domain/success/UserSuccess.java
> +public enum UserSuccess implements SuccessCode {
`p4`

해당 클래스는 정의된 내용이 없어보이는데 삭제해도 되는 파일 맞을까요??

2024-12-09 19:09 UTC, sung-silver commented on src/test/java/sopt/makers/authentication/usecase/auth/service/GetSocialAccountPlatformServiceTest.java
> +import static org.junit.jupiter.api.Assertions.*;
`p5`

여기도 와일드 카드..!

2024-12-09 19:09 UTC, sung-silver commented on src/test/java/sopt/makers/authentication/usecase/auth/service/GetSocialAccountPlatformServiceTest.java
> +    assertThat(resultForApple.platformName()).isEqualTo("APPLE");
`p3`

GOOGLE, APPLE 문자열을 상수로 분리하지 않으신 이유가 있을까요? 상수로 분리해도 이름이 같아서..?

2024-12-09 19:09 UTC, sung-silver commented on src/test/java/sopt/makers/authentication/usecase/auth/service/GetSocialAccountPlatformServiceTest.java
> +  void 주어진_Command에_대해_의도한_결과값을_반환한다() {
`p4`
현재 하나의 테스트에서 구글 플랫폼 조회, 애플 플랫폼 조회를 같이하고 있는데 각 플랫폼의 테스트에 대해 2개로 나누는 것은 어떨까요?

2024-12-10 12:05 UTC, yummygyudon commented on src/test/java/sopt/makers/authentication/usecase/auth/service/GetSocialAccountPlatformServiceTest.java
> +  void 주어진_Command에_대해_의도한_결과값을_반환한다() {
사실 분리하려고 했으나 플랫폼이 두 개 밖에 없었어서 하나에 하긴 했습니당 ㅋㅋㅋㅋ
분리를 해볼까요?!

2024-12-10 12:05 UTC, yummygyudon commented on src/test/java/sopt/makers/authentication/usecase/auth/service/GetSocialAccountPlatformServiceTest.java
> +    assertThat(resultForApple.platformName()).isEqualTo("APPLE");
앗 놓친 부분인 것 같습니다!! 상수화 해놓을게요!

2024-12-10 12:07 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/support/code/domain/success/UserSuccess.java
> +public enum UserSuccess implements SuccessCode {
음 삭제해도 괜찮겠네요!!
사용하는 곳은 없긴 하나 분명히 사용될 것이라는 빈약한 근거로 남겨놓긴했습니다만
생각해보니 사용되지 않는 객체의 소스코드는 불필요한 리소스 낭비가 될 수 있겠다는 생각이 듭니다!

2024-12-10 12:07 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/support/code/domain/success/AuthSuccess.java
>    AUTHENTICATE_SOCIAL_ACCOUNT(HttpStatus.OK, "소셜 로그인에 성공했습니다.");
오 좋은 의견 감사드립니다!!
`// 200` & `//201` 주석도 추가하도록 할게요!

2024-12-10 12:08 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/application/auth/api/SocialAccountApiController.java
> +  }
아차차 맞네요!!
이전에 작업햇던 api들도 반영해두겠습니다!!

2024-12-10 13:09 UTC, sung-silver approved these changes
수고하셨습니다!

2024-12-10 13:09 UTC, sung-silver commented on src/test/java/sopt/makers/authentication/usecase/auth/service/GetSocialAccountPlatformServiceTest.java
> +  }
`p5`

ParameterizedTest 사용하니까 테스트의 관심사를 잘 분리한 것 같아서 좋네요 ㅎ 리뷰 반영 감사드립니다

2024-12-10 22:50 UTC, hyunw9 approved these changes
고생하셨습니다 ! 

리뷰가 늦어져서 죄송합니다 .. ㅠ 

가독성 측면에서 짜잘한 리뷰 몇개 남겼습니다 !

2024-12-10 22:50 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/application/auth/api/AuthApiController.java
> +        AuthSuccess.VERIFY_PHONE_VERIFICATION, AuthResponse.VerifyResult.from(result));
`P4` 
수정해도 되고 안 수정해도 되지만 저는 요새 static import 해서 사용하고 있습니다 ! 
깔끔해지긴 하는거 같아요.

2024-12-10 22:50 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/support/security/filter/JwtAuthenticationFilter.java
> +        || url.contains(PATH_GET_REGISTER_SOCIAL_PLATFORM);
`P3` 

이 부분 개인적으로 Path 추가될 때 마다 static Import 가 필요해서 
List 형으로 Path 를 선언하고 `stream()` 으로 검사하면 어떨까 생각합니다!
 
```
List<String> EXCLUDED_PATHS = List.of(
    "/auth", "/actuator"
); 
...

return EXCLUDED_PATHS.stream().anyMatch(url::contains);
```

요런 느낌 어떤가요 ?

2024-12-12 15:21 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/application/auth/api/AuthApiController.java
> +        AuthSuccess.VERIFY_PHONE_VERIFICATION, AuthResponse.VerifyResult.from(result));
좋은 의견인 것 같습니다!!
반영해볼게요!

2024-12-12 15:22 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/support/security/filter/JwtAuthenticationFilter.java
> +        || url.contains(PATH_GET_REGISTER_SOCIAL_PLATFORM);
오 변동에 유연한 방법이겠네요!!
좋은 것 같습니다!! 바로 반영해볼게요!

2024-12-13 00:34 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/application/auth/api/AuthApiController.java
> +        AuthSuccess.VERIFY_PHONE_VERIFICATION, AuthResponse.VerifyResult.from(result));
아아으아! 근데 확인해보니까 
같은 Auth 관심사 내에서도 도메인별로 Success Code가 분리되어 있다보니까
Success 클래스를 명시하느 것이 좋을 것 같아요!! ㅋ킼ㅋ

그래도 좋은 제안 감사드립니다!

2025-01-06 12:21 UTC, merged