Feat/#5
sopt-makers/sopt-auth-backend pull request #6
Opened 2024-11-06 14:21 UTC by sung-silver

## Related Issue 🚀
- closed #5

## Work Description ✏️
- 이전에 논의한 내용을 바탕으로 공통으로 사용될 엔티티 3가지(UserActivityHistory, User, UserRegisterInfo)를 구현했습니다
![MAKERS_AUTHENTICATION](https://github.com/user-attachments/assets/c2cb0610-bb17-4602-b77c-f594c3165eba)

## PR Point 📸

- user_activity_histories와 users를 양방향으로 가져가야할 것도 같은게 toDomain 메서드를 user 엔티티에서 만들려고하니 activities를 만들어서 반환할수가 없더라고요.. 다른 분들의 의견이 궁금합니다!
- 회원가입 시점에 MemberEntity를 생성할 것으로 예상했는데, isActive 필드만 따로 파라미터로 받아도 될까요? 아니면 default는 false로 두고 업데이트를 하는게 나을까요?
- 엔티티 생성 시 builder 패턴을 쓸까요 아니면 그냥 생성자를 사용할까요? 또는 불변 객체를 사용해서 만든다는 무엇의 함수를 따로 정의하는게 나을지...
- user_register_info도 생성자가 필요할까요? 이건 회원가입 전에 저희가 db에 넣는 정보라고 생각하여 일단은 따로 만들지 않았습니다..!
- 저희 엔티티 뒤에 엔티티에는 불변 객체랑 구분하기 위해 Entity를 붙이기로했던 것 같은데 맞을까요? @yummygyudon 오빠의 이전 PR에 미리 생성한 PhoneVerification에는 붙이지 않아서 컨벤션을 맞추는게 좋을 것 같아 여쭤봅니다!

2024-11-07 10:38 UTC, yummygyudon approved these changes
작업 고생하셨습니다!!
코드에 달아놓은 리뷰와 더불어 몇 가지 궁금한 부분이 있어 남겨놓습니다!!

- 저희 검증 방식은 `springframework.boot:spring-boot-starter-validation` 을 쓰는 것으로 확정 지으면 될까요?!! (저는 좋음!! @hyunw9 의견도 궁금합니당)
  - 해당 어노테이션을 사용하며 ExceptionHandler를 사용하기 위해서는 `MethodArgumentNotValidException` 트래킹이 필요한 것으로 알아서요!!
  - 고려 가능한 방안 : `lombok.NonNull`, `jakarta.Nonnull` 등
- 전체적으로 Validation 라이브러리를 주입받은 것에 비해 활용하는 케이스가 많지 않은 것 같아요!! (_이건 살짝 리뷰 감성_)
- 전체적으로 Exception과 Error를 정의하지 않고 아직 IllegalException을 던지도록 하는 이유가 궁금합니다!!

2024-11-07 10:38 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/database/core/entity/UserActivityHistoryEntity.java
> +import lombok.*;
`P5`

와일드카드 import보다 사용되는 어노테이션들을 하나씩 주입받는 것은 어떻까요?!!
우선 기본적으로 보통의 java 컨벤션에서는 와일드 카드 import를 지양하기도 하고 어떤 라이브러리를 활용했는지 확인이 용이하다고 생각해서요!!

2024-11-07 10:38 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/database/core/entity/UserActivityHistoryEntity.java
> +  private UserEntity user;
`P5`

요친구 어노테이션 정렬하면 더 보기 좋을 것 같아요!!
```java
@NotNull
@JoinColumn(name = "user_id")
@ManyToOne(fetch = FetchType.LAZY)
private UserEntity user;
```

2024-11-07 10:38 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/domain/auth/User.java
> +  }
`P3`

`join`이라는 표현이라면 동일한 User와의 결합하는 메서드라고 오해할 소지가 존재하는 것 같아요!!
조금 더 명시적으로 `joinActivity` 혹은 `addActivity`/`addActivityHistory` 등의 이름은 어떨까요?!

2024-11-07 10:38 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/domain/auth/SocialAccount.java
> +  }
`P4`

1) 
주석 또한 지속적인 관리가 필요한 하나의 소스코드 자원이라고 생각합니다!!
메서드 명으로 충분히 전달할 수 있는 내용이라면 최대한 주석을 작성하지 않는 것은 어떨까요?!

예를 들어
"해당 메서드 안에서는 Platform에 대해 모든 요소를 검사하는 메서드야"라고 한다면
현 이름을 유지하고 앞으로 발생할 모든 검증 로직을 해당 메서드에 추가하고
"해당 메서드 안에서는 Platform Id만 검사하는 메서드야"라고 한다면
`validatePlatformId` 등으로 명시하는 것이 좋지 않을까 싶어요!!

2)
validate 내용을 확인해보니 null과 Empty 체크인 것 같은데
`@NotNull`, `@NotBlank` 를 Record 필드에 다는 방법으로 해결할 수 있을 것 같은데 별도 메서드로 구현한 이유가 궁금합니다!!

2024-11-07 10:50 UTC, yummygyudon commented
> - user_activity_histories와 users를 양방향으로 가져가야할 것도 같은게 toDomain 메서드를 user 엔티티에서 만들려고하니 activities를 만들어서 반환할수가 없더라고요.. 다른 분들의 의견이 궁금합니다!
"유저 정보"와 "활동 이력"은 각자 별도의 독립적인 도메인으로 관리할 수 있다고 생각합니다
꼭 도메인 내 도메인으로 의존하도록 만들 필요 없이 두개의 독립적인 불변 객체로 활용하는 것이 좋다고 생각해요

> - 회원가입 시점에 MemberEntity를 생성할 것으로 예상했는데, isActive 필드만 따로 파라미터로 받아도 될까요? 아니면 default는 false로 두고 업데이트를 하는게 나을까요?
- default는 false로 두고 추후 탈퇴할 경우에만 업데이트하는 것이 좋다고 생각합니다! (이건 @hyunw9 의견도 궁금!)

> - 엔티티 생성 시 builder 패턴을 쓸까요 아니면 그냥 생성자를 사용할까요? 또는 불변 객체를 사용해서 만든다는 무엇의 함수를 따로 정의하는게 나을지...
- 저는 생성자를 private으로 만들어두고 도메인 객체를 파라미터로 주입받아 생성하는 public static 생성 메서드를 정의하는 것이 좋다고 생각해요!! 도메인 객체를 통해서 만드는 것이 철저히 도메인 기반 Entity 관리가 가능하다고 생각해서요!
- `toDomain()` 메서드 좋다고 생각합니다

> - user_register_info도 생성자가 필요할까요? 이건 회원가입 전에 저희가 db에 넣는 정보라고 생각하여 일단은 따로 만들지 않았습니다..!
저는 생성하지 않아도 된다 생각합니다!!(접근제어자로 최대한 외부에서 생성자 생성이 불가능하도록 막아놓는 것도 괜찮아보여요!)
Getter만 만들어놓고 사용하면 될 것 같습니다!!

> - 저희 엔티티 뒤에 엔티티에는 불변 객체랑 구분하기 위해 Entity를 붙이기로했던 것 같은데 맞을까요? @yummygyudon 오빠의 이전 PR에 미리 생성한 PhoneVerification에는 붙이지 않아서 컨벤션을 맞추는게 좋을 것 같아 여쭤봅니다!

이해하신 바가 맞습니다!! 제가 깜빡한 것 같아요!! 저도 반영하도록 하겠습니다!!

2024-11-07 12:10 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/database/core/entity/UserActivityHistoryEntity.java
> +import lombok.*;
넵!

2024-11-08 05:57 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/database/core/entity/UserActivityHistoryEntity.java
> +import lombok.*;
domain, entity 와일드카드 삭제 후 모든 라이브러리 명시 완료했습니다!

2024-11-09 06:29 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/domain/auth/User.java
> +  }
joinActivity 혹은 등록하다의 의미를 가지는 enroll 도 좋아보입니다 !

2024-11-09 06:31 UTC, hyunw9 commented
늦게 확인했네요.. ㅎㅎ 

soft delete 시에는 최대한 오버헤드가 발생하지 않게, 삭제시에만 필드 입력을 받는 방식이 적절하다고 생각해요 ! 

-> default : false , 삭제 시 상태 변경이 좋은 거 같습니다 !

2024-11-10 07:03 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/domain/auth/SocialAccount.java
> +  }
1. 주석은 삭제하고 2번 내용은 회의 때 논의한 대로 `@NotNull` 어노테이션을 붙이도록 하겠습니다!

2024-11-10 07:06 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/domain/auth/User.java
> +  }
활동 이력 추가라는 의미가 드러나도록 joinActivity로 수정하겠습니다!

2024-11-10 10:01 UTC, sung-silver commented
1차 코드리뷰 반영사항을 정리했습니다!

1. 테이블 이름 컨벤션 통일했습니다.
2. 도메인 객체에서 lombok을 사용하여 생성자 접근 레벨을 private로 선언했고, Getter를 통해 조회할 수 있는 값을은 `@Getter`를 추가함으로써 메서드 내용을 삭제했습니다.
3. Record 불변객체에서 nullable한 값에 대하여 Optional 처리를 추가했습니다
4. empty, null에 대한 검증은 `@NotNull` 어노테이션을 붙여서 검증하도록 하였습니다
5. 서비스 내 커스텀 예외로 처리할 수 있도록 도메인 로직을 수정했습니다
- Domain Failure로 뺀 이유는 도메인 생성시 발생하는 이슈는 데이터베이스에 값을 누군가 조작하지 않는 이상 99.9% 클라이언트로부터 얻어오는 값에 대한 예외라고 생각했습니다
- 이에 따라 exception handler에서 예외를 잡았을 때 로깅을 굳이 해야할까 라는 생각이 들어 예외만 전달하고 로깅은 하지 않을 수 있도록 예외를 구분해보았어요!
- 현재 볼륨에서 도메인에서 처리하는 예외가 많지 않기도해서 일단은 큰 범주로 DomainFailure라고 정의해보았습니다 상세하게 나누어야 할 것 같다면 말씀해주세요!
6. 엔티티 생성 시 불변 객체를 사용하여 생성할 시에는 fromDomain, 엔티티를 불변 객체로 변환할 시에는 toDomain을 사용하도록 메서드를 정의했습니다


다음은 코드리뷰를 반영 및 코드를 변경하며 들었던 궁금증과 의견을 여쭤보고자하는 내용입니다!
- createNewUser에서는 Builder를 사용하고, update에서는 생성자를 사용하는 이유가 생성에서는 각 요소에 어떤 값이 들어가는지 강조하기 위함인지 궁금합니다 @hyunw9 
- RegisterInfomation과 Profile의 내용이 많이 유사하다는 생각이 드는데 해당 클래스는 어떤 용도로 만드신건지 궁금합니다 @yummygyudon 
- `@all` 일단은 존재하지 않는 ~입니다 라는 예외는 찾을 수 없다는 의미가 더 강한 것 같아서 NOT_FOUND로 HttpStatus를 처리했는데요. 개인적으로 저는 서비스내에서 정의되지 않는 값으로 요청을 보내면 모두 BAD_REQUEST로 처리하긴하는데 두분의 스타일이 궁금합니다! 만약 저와 같은 생각이시라면 존재하지 않는 ~입니다 -> 유효하지 않은 ~입니다 & HttpStatus를 BAD_REQUEST로 변경해도 괜찮을까요?

2024-11-11 15:25 UTC, yummygyudon approved these changes
코드 측면에서 좋은 것 같습니다!!
고생하셨어요!

2024-11-11 15:25 UTC, yummygyudon commented on src/main/java/sopt/makers/authentication/domain/auth/ActivityList.java
> +            });
`P5`

개인적인 선호도이기는 한데
람다식에서 변수명은 구체적으로 명시하는 걸 선호하는 편이라
해당 람다식을 예시로 든다면 `a` 보다는 `existActivity` 등으로 명시하는 것은 어떨지 제안드려봅니다!

여러분들의 의견이 궁금합니다!!(cc. @sung-silver )

2024-11-11 15:37 UTC, yummygyudon commented
> 1차 코드리뷰 반영사항을 정리했습니다!
> 
> 1. 테이블 이름 컨벤션 통일했습니다.
> 2. 도메인 객체에서 lombok을 사용하여 생성자 접근 레벨을 private로 선언했고, Getter를 통해 조회할 수 있는 값을은 `@Getter`를 추가함으로써 메서드 내용을 삭제했습니다.
> 3. Record 불변객체에서 nullable한 값에 대하여 Optional 처리를 추가했습니다
> 4. empty, null에 대한 검증은 `@NotNull` 어노테이션을 붙여서 검증하도록 하였습니다
> 5. 서비스 내 커스텀 예외로 처리할 수 있도록 도메인 로직을 수정했습니다
> 
> * Domain Failure로 뺀 이유는 도메인 생성시 발생하는 이슈는 데이터베이스에 값을 누군가 조작하지 않는 이상 99.9% 클라이언트로부터 얻어오는 값에 대한 예외라고 생각했습니다
> * 이에 따라 exception handler에서 예외를 잡았을 때 로깅을 굳이 해야할까 라는 생각이 들어 예외만 전달하고 로깅은 하지 않을 수 있도록 예외를 구분해보았어요!
> * 현재 볼륨에서 도메인에서 처리하는 예외가 많지 않기도해서 일단은 큰 범주로 DomainFailure라고 정의해보았습니다 상세하게 나누어야 할 것 같다면 말씀해주세요!
> 
> 6. 엔티티 생성 시 불변 객체를 사용하여 생성할 시에는 fromDomain, 엔티티를 불변 객체로 변환할 시에는 toDomain을 사용하도록 메서드를 정의했습니다
> 

모두 확인했습니다!
다만 클라이언트로부터 얻어오는 값에 대한 예외라고 하더라도
클라이언트가 "**전달한 값 중 어떤 값이 어떤 이유로 예외가 발생했는지**" 파악해야하지 않나 싶어서
`이에 따라 exception handler에서 예외를 잡았을 때 로깅을 굳이 해야할까 라는 생각이 들어 예외만 전달하고 로깅은 하지 않을 수 있도록`이 어떤 의도인지 조금 궁금합니다!!

> * createNewUser에서는 Builder를 사용하고, update에서는 생성자를 사용하는 이유가 생성에서는 각 요소에 어떤 값이 들어가는지 강조하기 위함인지 궁금합니다 @hyunw9

저도 이부분 궁금하긴 하네요!(@hyunw9 )

추가적으로 접근제어자를 확실하게 활용하여 객체 생성 경로를 의도에 따라 제한하고자 한다면 아래와 같이 변경하는 것은 어떨까 싶어요!
```java
@RequiredArgsConstructor(access=PRIVATE)
@Builder(access=PRIVATE)
public class User {

    public static User createNewUser(
      long id, final SocialAccount socialAccount, final Profile profile) {
        return. User.builder()
            .id(id)
            .socialAccount(socialAccount)
            .profile(profile)
            .activities(new ActivityList())
            .build();
      }

    public User updateSocialAccount(final SocialAccount socialAccount) {
        return. User.builder()
            .id(this.id)
            .socialAccount(socialAccount)
            .profile(this.profile)
            .activities(this.activities)
            .build();
    }
}
```

> * RegisterInfomation과 Profile의 내용이 많이 유사하다는 생각이 드는데 해당 클래스는 어떤 용도로 만드신건지 궁금합니다 @yummygyudon

`RegisterInfomation`의 경우, 이관 과정에서 판단하여 구현한 것은 "임원진이 전달한 명단 데이터" 객체이긴 합니다.
만약 `Profile`이 위 쓰임과 동일하다면 제거하셔도 됩니다!

> * `@all` 일단은 존재하지 않는 ~입니다 라는 예외는 찾을 수 없다는 의미가 더 강한 것 같아서 NOT_FOUND로 HttpStatus를 처리했는데요. 개인적으로 저는 서비스내에서 정의되지 않는 값으로 요청을 보내면 모두 BAD_REQUEST로 처리하긴하는데 두분의 스타일이 궁금합니다! 만약 저와 같은 생각이시라면 존재하지 않는 ~입니다 -> 유효하지 않은 ~입니다 & HttpStatus를 BAD_REQUEST로 변경해도 괜찮을까요?

"서비스내에서 정의되지 않는 값으로 요청"은 저 또한 모두 BAD_REQUEST로 처리합니다!! (서버에 정의되어 있지 않은 스펙의 요청이기 때문)
하지만 "존재하지 않는다"와 "유효하지 않다"는 엄연히 다른 의미라고 생각해요!!
(ex. id = 1로 요청이 왔을 때, 값은 정상적인 id 데이터 타입 및 형식이기 때문에 "유효"하지만 해당하는 유저가 없다면 "존재하지 않은 것")


이에 "존재하지 않는 ~입니다 -> 유효하지 않은 ~입니다"이라고 변경하는 것은 의미를 더 명확히 판단해서 결정하는 것이 좋을 것 가탕요!

2024-11-12 13:14 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/domain/auth/ActivityList.java
> +            });
오 좋은 것 같습니다!! 반영할게요

2024-11-12 13:21 UTC, sung-silver commented
> 모두 확인했습니다! 다만 클라이언트로부터 얻어오는 값에 대한 예외라고 하더라도 클라이언트가 "**전달한 값 중 어떤 값이 어떤 이유로 예외가 발생했는지**" 파악해야하지 않나 싶어서 `이에 따라 exception handler에서 예외를 잡았을 때 로깅을 굳이 해야할까 라는 생각이 들어 예외만 전달하고 로깅은 하지 않을 수 있도록`이 어떤 의도인지 조금 궁금합니다!!

클라이언트에서 정의한대로 요청이 들어온다면 파라미터 값이 잘못되서 발생하는 예외가 아니라 임의의 누군가가 저희 API 엔드포인트를 확인하고 postman이나 다른 툴로 조작을 하여 요청을 보낼것이라고 생각해요! 그래서 이 부분에 대해 특정 값 때문에 예외가 발생했다는 것에 대한 정보를 전달하지 않는것은 어떤지?에 대한 의미를 담은 말이었습니다..! 조금 헷갈릴 수 있겠네요 그리고 저런 조작 요청은 저희가 핸들러 메서드 내에서 로깅하여 하나하나 대응할 필요가 없다고 생각했습니다. API 붙이는 과정에서 에러가 발생했다면 파라미터가 잘못된 경우는 명세서를 통해서 충분히 확인 가능한 부분이라는 생각도 들었고요!

> 추가적으로 접근제어자를 확실하게 활용하여 객체 생성 경로를 의도에 따라 제한하고자 한다면 아래와 같이 변경하는 것은 어떨까 싶어요!
> 
> ```java
> @RequiredArgsConstructor(access=PRIVATE)
> @Builder(access=PRIVATE)
> public class User {
> 
>     public static User createNewUser(
>       long id, final SocialAccount socialAccount, final Profile profile) {
>         return. User.builder()
>             .id(id)
>             .socialAccount(socialAccount)
>             .profile(profile)
>             .activities(new ActivityList())
>             .build();
>       }
> 
>     public User updateSocialAccount(final SocialAccount socialAccount) {
>         return. User.builder()
>             .id(this.id)
>             .socialAccount(socialAccount)
>             .profile(this.profile)
>             .activities(this.activities)
>             .build();
>     }
> }
> ```

좋은 의견 감사합니다!

> `RegisterInfomation`의 경우, 이관 과정에서 판단하여 구현한 것은 "임원진이 전달한 명단 데이터" 객체이긴 합니다. 만약 `Profile`이 위 쓰임과 동일하다면 제거하셔도 됩니다!

아하 이해했습니다! 

> "서비스내에서 정의되지 않는 값으로 요청"은 저 또한 모두 BAD_REQUEST로 처리합니다!! (서버에 정의되어 있지 않은 스펙의 요청이기 때문) 하지만 "존재하지 않는다"와 "유효하지 않다"는 엄연히 다른 의미라고 생각해요!! (ex. id = 1로 요청이 왔을 때, 값은 정상적인 id 데이터 타입 및 형식이기 때문에 "유효"하지만 해당하는 유저가 없다면 "존재하지 않은 것")
> 
> 이에 "존재하지 않는 ~입니다 -> 유효하지 않은 ~입니다"이라고 변경하는 것은 의미를 더 명확히 판단해서 결정하는 것이 좋을 것 가탕요!

제가 생각하는 유효의 의미는 서비스에서 의도한 동작인가?를 생각한거긴한데 다른 분들의 의견도 궁금하긴 하네요!

2024-11-12 17:11 UTC, yummygyudon commented
> 클라이언트에서 정의한대로 요청이 들어온다면 파라미터 값이 잘못되서 발생하는 예외가 아니라 임의의 누군가가 저희 API 엔드포인트를 확인하고 postman이나 다른 툴로 조작을 하여 요청을 보낼것이라고 생각해요! 그래서 이 부분에 대해 특정 값 때문에 예외가 발생했다는 것에 대한 정보를 전달하지 않는것은 어떤지?에 대한 의미를 담은 말이었습니다..! 조금 헷갈릴 수 있겠네요 그리고 저런 조작 요청은 저희가 핸들러 메서드 내에서 로깅하여 하나하나 대응할 필요가 없다고 생각했습니다. API 붙이는 과정에서 에러가 발생했다면 파라미터가 잘못된 경우는 명세서를 통해서 충분히 확인 가능한 부분이라는 생각도 들었고요!

흠 일리가 있는 의견인 것 같네요...!!
"문제가 생겼을 때 원인 파악을 하기 위해선 백엔드의 확인 및 도움이 항상 필요하다"라는 우려가 있긴 하지만
**아래의 근거 하에 상세 원인을 로그로 남긴다면** 성은이의 의견이 맞는 것 같다는 생각이에요!!
- 로그 모니터링 서버가 존재한다면 접속해서 클라이언트도 확인 가능
- 로그 확인은 당연히 해주어야 하는 임무이기 때문에 불편하더라도 상관 없음


(추가)
우리 인증서버도 LogBack 적용할거죠?!

2024-11-14 01:32 UTC, hyunw9 requested changes
전체적인 부분은 이미 진행된 것 같아서 디테일 위주와 질문하신 부분에 대한 답변을 중점적으로 남겨놓겠습니다 ! 

남겨주신 질문에 대한 답변입니다 !
1. createNewUser에서는 Builder를 사용하고, update에서는 생성자를 사용하는 이유가 생성에서는 각 요소에 어떤 값이 들어가는지 강조하기 위함인지 궁금합니다 
- 우선 맞습니다 ! 하지만 위에 말씀해주신 대안을 활용하는 것이 더 적절하다 생각합니다. 
2. 이에 따라 exception handler에서 예외를 잡았을 때 로깅을 굳이 해야할까 라는 생각이 들어 예외만 전달하고 로깅은 하지 않을 수 있도록 하기 
- 흠.. 제 생각은 일단 로깅은 남겨 놓는 것이 좋지 않나? 의 입장입니다. 

-근거-
1. 로그를 하지 않았을 때의 비용 > 로그를 남겼을 때의 비용 
이 부분은 위에서 동규형이 말씀하신 대로 특정에러가 발생했을 때 저희가 대신해서 확인해야 하는 부분이 생길 것 같은데요 ! 
물론 운영 상황에선 에러가 발생할 여지가 적지만, 그 이유는 클라 - 백엔드가 운영 이전에 무수히 에러 상황에 대한 처리와 대비를 진행하며 개발을 해놨기 때문이라고 생각합니다! 
그러한 관점에서는 로그를 남겨놓는게 더 프로세스 진행 측면에서 비용이 적게 들지 않나 싶습니다 ! 
외부 솔루션 사용도 가능할 것 같구요 !

2024-11-14 01:32 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/database/core/common/BaseTimeEntity.java
> +  @CreatedDate
`P5`
사소한 개행 추가 부탁드립니다

2024-11-14 01:32 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/database/core/entity/UserEntity.java
> +
`P5`

여기도 정렬 부탁드립니다!!

2024-11-14 01:32 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/domain/auth/Activity.java
> +    if (this.role.isPartRequired() && this.part.isEmpty()) {
`P4`
변수화해서 빼도 좋을것 같습니다 !

2024-11-14 01:32 UTC, hyunw9 commented on src/main/java/sopt/makers/authentication/database/core/entity/UserRegisterInfoEntity.java
> +  private int generation;
`P5` 
여기도 아마 자동정렬이 되지 않았나 싶슴다!!

2024-11-14 06:55 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/database/core/common/BaseTimeEntity.java
> +  @CreatedDate
변수랑 클래스 선언부 사이는 붙여서 정의하는게 컨벤션으로 알고 있습니다..! 그리고 변수 선언부는 모두 붙여써야하는데 어노테이션을 붙이면 포매터에서 자동으로 띄우는 것 같더라고요 그래서 저도 이 부분에 대해서는 앞으로 리뷰에 남기지 않도록 하겠습니다!

2024-11-14 06:55 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/domain/auth/Activity.java
> +    if (this.role.isPartRequired() && this.part.isEmpty()) {
넵 확인했습니다!

2024-11-14 06:55 UTC, sung-silver commented on src/main/java/sopt/makers/authentication/database/core/common/BaseTimeEntity.java
> +  @CreatedDate
해당 리뷰와 관련된 내용은 resolve하겠습니다!

2024-11-14 12:16 UTC, hyunw9 approved these changes

2024-11-14 12:19 UTC, merged